<div class="modal fade">
   
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3>ALANADI KAYIT SÖZLEŞMESİ</h3>
  </div>

  <div class="modal-body">
      <p>
<p class="p1"><span class="s1">ALANADI KAYIT SÖZLEŞMESİ</span></p>
<p class="p2">&nbsp;</p>
<p class="p1"><span class="s1">Bu sözleşme aşağıda bilgileri bulunan taraflar arasında elektronik ortamda kabul edilmiş ve imzalanmıştır.&nbsp; Taraflar arasında çıkabilecek bütün ihtilaflar aşağıdaki hükümler çerçevesinde çözüm bulacaktır.</span></p>
<p class="p1"><span class="s1">Taraflar:</span></p>
<ol class="ol1">
<li class="li1"><span class="s1">Alveal Yay. Ltd. Şti. (Bundan sonra Alveal olarak anılacaktır.)<br> Adres: Ufuktepe mh. Sevenler sok. No:2/17 Keçiören / Ankara<br> Tel: +90 (312) 580 37 47<br> Mail: satis@sincapp.com</span></li>
<li class="li3"><span class="s2"></span><span class="s1">Müşteri (Bundan sonra Müşteri olarak anılacaktır.)<br>
Adı Soyadı: <?php echo $contact->name?><br>
Adresi: <?php echo $contact->address?><br>
Tel: <?php echo $contact->phone?><br>
Mail: <?php echo $contact->email?></span></li>
</ol>
<p class="p3"><span class="s1">Adı geçen sözleşme Alveal ile Müşteri arasında elektronik yürürlük tarihinden itibaren yürürlüğe girmiştir. Bu Sözleşme, Müşteri’nin Alveal üzerinden sağladığı veya sağlayacağı Alan Adı Tahsisi/ Kayıt hizmetinin kullanımına ilişkin kayıt ve şartları ortaya koyar ve Genel Servis Şartlarının yanı sıra Müşteri ile Alveal arasındaki nihai anlaşma şartlarını kapsar. Adı geçen sözleşmenin sanal ortamda imzalanmasını/kabulünü/onayını takiben de Müşteri bu sözleşmenin imzalanmasına/kabulüne/onayına katılmak suretiyle, sözleşmeyi, sözleşmenin yanı sıra Alveal Hizmet Sözleşmesi Genel Hükümlerini de bu sözleşmeden ayrılmaz ve bölünemez bir bütün olarak, okuyup, anladığınızı ve uyuşmazlık politikaları bakımından Yetkili Kayıt Operatörü’nün devir ve uyuşmazlık çözüm politikası ve ile Alveal’in zaman zaman <a href="http://www.alveal.com"><span class="s3">www.alveal.com</span></a> ve www.sincapp.com isimli alan adları üzerinde yapacağı güncellemeler ve düzenlemeleri de kapsayan ilave ya da farklı kayıt, şart ve politikalar da dahil olmak üzere işbu Sözleşmedeki bütün kayıt ve şartlara bağlı kalmayı, bütün kayıt ve şartlara uygun davranmayı kabul, beyan ve taahhüt ettiğini onaylamaktadır.</span></p>
<p class="p3"><span class="s1">Müşteri ve Alveal, müşteriye tahsis edilen alan adı bakımından gerek müracaat esnasında gerek tahsis esnasında gerekse sonrasında tasarrufta bulunmaya yetkili yegane kişinin müşteri olduğunu kabul ederler. Ancak Tüzel Kişiler bakımından yetkili kişinin yalnız ve ancak şirketi temsil ve ilzama yetkili kişi/kişiler olduğu tarafların kabulündedir. Müşterinin hesabında, müşteri ya da yetkili kişiler tarafından yapılan işlemlere ek olarak, alan adı veyahut e-mail şifrelerini, kullanıcı bilgilerini, sair kişisel verilerine sahip, Alveal Müşteri Temsilcisini, çalışanlarını, call center görevlilerini, uzaktan destek ekiplerini kısaca Alveal çalışanlarını veyahut Alveal’in doğrudan veyahut dolaylı yoldan müşteri hizmeti sağlamak üzere anlaştığı 3. Kişileri, Müşteri veyahut müşterinin yasal temsilcisi olduğunu ispat edebilen veyahut kuvvetli bir biçimde ortaya koyan kişilerin veyahut Müşterinin 1. Dereceden kan veya sıhri hısımı olduğuna ikna edebilecek veyahut temsilci olarak hareket eden 3. bir kişinin yaptığı işlemlerle ve Alveal üzerinden tahsis edilmiş alan adları bakımından tesis ettiğiniz hesabınızı veyahut alan adını veya şifrelerini kullanan herhangi bir kişinin Müşteri menfaatine olsun ya da olmasın yapacağı işlemlerle bağlı olduğunu kabul etmektedir.</span></p>
<p class="p3"><span class="s1">Müşteri, gerek Alveal’nun, gerek Yetkili Kayıt Operatörü’nün koymuş olduğu kurallar ile bağlı olduğunu kabul etmektedir. Müşteri, ICANN ve/veya ICANN tarafından seçilmiş Kayıt Yetkilisi tarafından belirlenen kayıt ve şartlar ve ilgli mevzuata ve Alveal tarafından zaman zaman yayınlanacak bütün kayıt kuralları ve politikalarına uyabilmek için bu sözleşmede değişiklik yapabileceğini kabul etmektedir.</span></p>
<p class="p3"><span class="s1">ÜCRETLER</span></p>
<p class="p3"><span class="s1">Müşteri tarafından satın alınan ve Alveal tarafından Müşteriye sağlanan hizmet ve ürünler karşılığında, Müşteri; Alveal'dan hizmeti talep ettiği anda ödeme yapmayı kabul etmektedir. Ödeme, Müşteri tarafından aşağıdaki yollardan biri ile yapılır: geçerli bir kredi kartı, havale, eft.</span></p>
<p class="p3"><span class="s1">Ödeme zamanında, döviz cinsi üzerinden yapılacak ödemeler bakımından Türkiye Cumhuriyeti Merkez Bankasının Amerikan Doları Döviz Satış Kuru üzerinden ödeme yapılmalıdır. Alan adı kayıt hizmeti satın alındığında, Alveal, herhangi bir sebeple, sağladığı hizmetlerin bedelini müşteriden tam olarak tahsil edemezse veya önceden tahsil ettiği herhangi bir ücret için kendisine yapılan ödeme ile ilgili herhangi bir sıkıntı ile karşı karşıya kalırsa (örneğin çalıntı kredi kartı ile yapılan ödemeler) Müşteri, Alveal’in ödemeyi tahsil bakımından tüm idari, usuli, yargısal ve cezai çarelere başvurabileceğini bildiğini kabul ve beyan eder.</span></p>
<p class="p3"><span class="s1">Müşteri çalıntı kredi kartı ile yapılan alış veriş bakımından çalıntı kredi kartı ile yapılan alış veriş tek bir alış veriş olsa dahi Alveal'in etkin bir ödemeyi sağlamak için takip edeceği çareler arasında, ve bu önlemlerle sınırlı olmamak üzere, Müşteri hesabınıza kayıtlı olan veya süresi uzatılmış olan bütün alan adları ve almış olduğunuz sair hizmetlerin herhangi bir bildirim olmaksızın derhal iptal edilebileceğini, durdurulabileceğini, herhangi bir zarar ziyan tazmin mükellefiyeti doğurmaksızın Müşteri kaydınız da dahil olmak üzere aldığınız tüm hizmet ve mal kalemlerinin bedeli ne olursa olsun iptal edilebileceğini, son verilebileceğini, durdurulabileceğini kabul, beyan ve taahhüt etmektedir.</span></p>
<p class="p3"><span class="s1">Alveal, düzenli hizmetlerinin kapsamı dışındaki sair görevler bakımından ve ek hizmet veyahut mal talepleri bakımından her zaman makul bir hizmet ücreti tahsil etme hakkını saklı tutar. Bunlar, burada sayılanlarla sınırlı olmamak üzere, e-posta üzerinden halledilemeyen ve kişisel hizmet gerektiren müşteri hizmetleri sorunları ve özel hizmet gerektiren anlaşmazlıklar veyahut Alveal’in Müşteri bakımından almak zorunda kaldığı hukuk müşavirliği vb. hizmetlerdir. Bu tahsilatlar, Müşterinin Alveal’da kayıtlı olan Ödeme Yöntemine mümkün olduğunca uygun biçimde fatura edilecektir.</span></p>
<p class="p3"><span class="s1">Alan Adı Süre Uzatımları </span></p>
<p class="p3"><span class="s1">Bir alan adı müşteriye tahsis edildiği zaman - müşteri adına kayıt olduğu zaman adı geçen alan adı bakımından süre uzatımı yalnız ve ancak iki şekilde olabilir. Bunlardan ilki müşterinin otomatik ödeme talimatı verdiği diğeri de müşterinin kendiliğinden müşteri panelinden alan adının süresini uzattığı durumlardır. Bunun dışındaki haller için Alveal alan adı süre uzatımı bakımından müşteriye herhangi bir taahhütte bulunamaz.</span></p>
<p class="p3"><span class="s1">Eğer herhangi bir nedenle Alveal, Müşteri bilgilerinde kayıtlı Ödeme bilgilerinden ödemesini alamazsa veyahut Müşteri Alveal’in ödeme almasını onaylamazsa Müşteri Alveal’nun yapmış olduğu bildirimleri cevaplamazsa, Müşteri alan adı kaydı sona erecektir.</span></p>
<p class="p3"><span class="s1">Müşteri kredi kartı ile alış veriş yapıyorsa Alveal’in sistemlerindeki kredi kartı bilgilerini, son kullanım tarihi bilgisini içeren Ödeme Yöntemi bilgisini güncel tutmak zorundadır.</span></p>
<p class="p3"><span class="s1">Alan adı süresi uzatılmayacaklar statüsünde olduğu zaman, Müşteri alan adının süresini, sadece, Alveal'i arayarak ve alan adının süresinin uzatılması isteğini ileterek uzatabilir. Müşteri talimatı olmaksızın alan adının süresi ilgili Müşteri Yöneticisi tarafından düzeltilemez. Eğer Müşteri, alan adı bitiş tarihinden önce süre uzatımı uygulamasını yapmazsa, alan adı iptal edilecek ve artık bu alan adını kullanamayacaktır.</span></p>
<p class="p3"><span class="s1">Müşteri, bu Sözleşme‘de belirtilen zaman dilimleri içerisinde gerek otomatik olarak gerekse kendisi süre uzatımını yapmadığı alan adlarının iptal edilmesinden dolayı Alveal'in sorumlu olmayacağını kabul etmektedir. Her halükarda, alan adınızın süresini zamanında uzatmazsanız, ilave ücretler uygulanabilir. Eğer müşteri, alan kaydı hizmeti ile birlikte alan adı maskeleme, alan adı yönlendirme veya benzeri bir hizmeti de Alveal’dan alıyorsa, Müşteri alan adı kayıt süresinin sona ermesiyle aldığı diğer hizmetlerin de sürelerinin otomatik olarak sona ereceğini kabul ve beyan eder.</span></p>
<p class="p3"><span class="s1">Müşteri, bu Sözleşme‘de belirtilen zaman dilimlerinde alan adının süresini uzatmadığı takdirde, Alveal'in, kendi takdir yetkisine bağlı olarak, Müşteriye ait süresi dolmuş alan adının süresini kendiliğinden uzatabileceğini kabul etmektedir. Eğer, Alveal, Müşterinin süresi dolmuş alan adının süresini uzatmaya karar verirse, Alveal Müşterinin alan adını koruduğu ve süresini uzattığı için Müşteri Alveal'ya ödeme yapabileceği bir Süre Uzatım Mühleti'ne sahip olacaktır. Süre Uzatım Mühleti: 30 gündür.</span></p>
<p class="p3"><span class="s1">Alan adının süresi dolduktan sonra Süre Uzatım Mühleti verilmesi bütün alan adı uzantıları için geçerli değildir.</span></p>
<p class="p3"><span class="s1">Eğer Müşteri Süre Uzatım Mühleti esnasında, süre uzatım için Alveal'a ödeme yapmazsa, alan adı, Alveal'a bir geri alım ücreti ödemek sureti ile alan adını geri alması için müşteriye 30 günlük bir ödeme müddeti tanındıktan sonra, beklemeye alınarak, silinmek üzere işaretlenecektir. Geri alma ücreti alan adı uzantısına göre 40USD ile 120USD arasındadır. Eğer Müşteri alan adı için, 30 günlük ödeme müddetinin bitmesinden önce ödeme yapmaz ise Alveal, kendi takdir yetkisine bağlı olarak, Müşterinin alan adını silebilir veya Müşteri hesabının bir başka kişiye devredilebilmiş olma ihtimalini kabul eder.</span></p>
<p class="p3"><span class="s1">Eğer Müşterinin alan adı silinirse, Alveal'a bir geri alma ücreti ödeyerek, Merkezi Kayıt Operatör’ü Müşteriye alan adını geri alması için 30 günlük bir Ödeme Mühleti sağlar. Geri alma ücreti alan adı uzantısına göre 40USD ile 120USD arasındadır. Eğer alan adınız için, Ödeme Mühleti'nin bitmesinden önce ödeme yapmazsanız, Müşteri alan adınızın serbest bırakılacağını ve ilk gelenin alıp üzerine kaydettirmesine açık hale geleceğini kabul ettiğiniz bilgileriniz dahilindedir.</span></p>
<p class="p3"><span class="s1">Süre Uzatım Mühletleri ve Ödeme Mühletleri alan adı uzantılarına göre farklılık gösterebilir.</span></p>
<p class="p3"><span class="s1">SÖZLEŞME ŞARTI; DEĞİŞİKLİKLER</span></p>
<p class="p3"><span class="s1">Bu Sözleşme'nin süresi, müşteri, Alveal aracılığıyla alan adı kaydettirdiği sürece tam, güçlü ve etkin bir şekilde hüküm ifade eder. Müşteri Alveal aracılığıyla kaydettirdiği her hangi bir alan adını, kaydın başlangıç tarihinden sonraki ilk altmış (60) gün içinde bir başka alan adı Kayıt Operatörü’ne devredemeyeceğini kabul etmektedir.</span></p>
<p class="p3"><span class="s1">Müşteri, Alveal'in, bu Sözleşme'de zaman zaman değişiklikler, güncellemeler yapabileceğini kabul etmektedir. Alveal, bununla beraber bu Sözleşme kapsamında sağladığı hizmetleri durdurabilir. Müşteri, bu gibi değişikliklerin etkisiyle, Alveal'in bu Sözleşme'de yapacağı makul değişikliklerle bağlı olmayı kabul etmektedir. Müşteri Alveal ile olan sözleşmesini iptal etmeyi seçerse, Alveal'a yapmış olduğu hiçbir ödemeyi iade alamayacağı bilgileri dahilindedir.</span></p>
<p class="p3"><span class="s1">GÜNCEL BİLGİ; BİLGİNİN KULLANIMI VE SÜRE BİTİMİ</span></p>
<p class="p3"><span class="s1">Müşteri, uygulamanın ve/veya kayıt süreç değişikliklerinin bir parçası olarak her hangi bir bilgi edindiği zaman bunu iki (2) işgünü içinde Alveal 'a bildireceğini kabul etmektedir. Bu bilgiyi güncel ve doğru bir durumda korumak Müşterinin sorumluluğundadır. Her ne sebeple olursa olsun, Alveal'a başlangıçta ve devamlı olarak kesin ve doğru bilgiyi sağlayamamanız, bu Sözleşme'nin esaslı olarak ihlali manasına gelir. Müşteri tarafından sağlanan bilginin geçerliliğine karar vermek için Alveal tarafından müşteriye yöneltilecek her hangi bir soruya, her ne sebeple olursa olsun, ilk iki (2) gün içinde cevap vermemeniz, bu Sözleşme'nin esaslı olarak ihlali manasına gelir. Kaldı ki her halükarda Müşteri Alan adının satın alma kaydının bir kopyasının tutulmasını kabul etmektedir.</span></p>
<p class="p3"><span class="s1">Müşteri, üzerine kaydedilmiş her bir alan adı için aşağıdaki iletişim verilerini sağlamayı kabul etmektedir: eğer kayıtlı alan adı sahibi ile iletişim kurulacaksa ona ait posta adresi, e-posta adresi, telefon numarası ve varsa faks numarası; ve eğer kayıtlı alan adı sahibinden farklı ise aynı iletişim bilgileri teknik yetkili, idari yetkili ve ödeme yetkilisi içinde sağlanmalıdır.</span></p>
<p class="p3"><span class="s1">Müşteri, kayıt operatörüyle paylaşılacak bu iletişim bilgilerinin alan adı kaydı için gerekli olduğunu bilir ve kabul eder. ICANN'ın istediği bu bilgi Whois yoluyla halka açık olması ve kayıt operatörünün Whois yoluyla bu bilgiyi halka açık tutması gerekebilir. Gerek Alveal gerekse kayıt operatörü, bu bilgiyi güvenilir bir üçüncü kişiyle beraber arşivleyebilir. İşbu şekilde müşteri, bütün bu ihtiyaç ve bildirimlere onay ve rıza vermektedir.</span></p>
<p class="p3"><span class="s1">Müşteri, üzerine kayıtlı her bir alan adı için, aşağıdaki bilgilerin, ICANN Politikası gereğince, belirlenmiş olan Whois dizininde halka açık olarak yer alacağını ve ICANN sözleşmesinde belirlenen şekilde bütün olarak ticari amaçla kullanılabileceğini, bir katalogda yer alabileceğini, satılabileceğini kabul etmektedir.</span></p>
<p class="p3"><span class="s1">• Alan Adı </span></p>
<p class="p3"><span class="s1">• İsminiz ve posta adresiniz </span></p>
<p class="p3"><span class="s1">• E-posta adresi, posta adresi, teknik ve idari iletişimler için telefon ve faks numaraları </span></p>
<p class="p3"><span class="s1">• Birincil ve İkincil Ad Sunucuları (Name Server) için İnternet Protokol Numaraları </span></p>
<p class="p3"><span class="s1">• Ad Sunucularının cevap veren isimleri ve </span></p>
<p class="p3"><span class="s1">• Orijinal Kayıt ve süre bitim tarihi </span></p>
<p class="p3"><span class="s1">Müşteri, alan adı kayıt sürecinde sağladığı kamuya açık bilgilerin, ICANN'ın izin verdiği kapsamda, Alveal tarafından kullanılabileceğini kabul etmektedir.</span></p>
<p class="p3"><span class="s1">Müşteri aynı zamanda alan adı sistemleri konusunda gerek mevcut gerek gelecekteki kural ve politikalarla uyumlu olmak bakımından, alan adı başvurusu yaptığı sırada sağladığı aşağıda yer alan bilgileri, interaktif ve kamuya açık bir biçimde, kendi veri tabanı aracılığıyla üçüncü kişilere açıklayabilme hakkını Alveal’a vermektedir.</span></p>
<p class="p3"><span class="s1">i. Müşteri tarafından kaydedilmiş alan adı ya da alt alan ad(lar)ı </span></p>
<p class="p3"><span class="s1">ii. Organizasyonunuzun adı, tipi ve posta adresi</span></p>
<p class="p3"><span class="s1">iii. Alan ad(lar)ınız veya alt-alan ad(lar)ınız için idari ve teknik sorumluların ad(lar)ı, pozisyon(lar)ı, posta adres(ler)i, e-posta adres(ler)i, sesli telefon numara(lar)ı ve varsa fax numara(lar)ı. </span></p>
<p class="p3"><span class="s1">iv. Alan adınız veya alt-alan adınız için en az iki (2) ad sunucusu hostunun (biri birincil ve en az biri ikincil) tüm host adları ve internet protokol adresleri ad sunucusu belirtilebilir.</span></p>
<p class="p3"><span class="s1">v. bu ad sunucuların cevap veren isimleri </span></p>
<p class="p3"><span class="s1">vi. kaydın Orijinal oluşum tarihi ve </span></p>
<p class="p3"><span class="s1">vii. kaydın süre bitim tarihi </span></p>
<p class="p3"><span class="s1">Alveal’nun bu ve buna benzer bilgileri bütün halinde veya bir kısmını üçüncü kişilerin kullanımına açması gerekebilir. Bununla beraber, takdir hakkı Alveal’a ait olmak üzere, bu bilgiyi bir üçüncü kişiye devredebilir veya temlik edebilir.</span></p>
<p class="p3"><span class="s1">UYUŞMAZLIK ÇÖZÜM POLİTİKASI</span></p>
<p class="p3"><span class="s1">Müşteri, Alveal’in halihazırda var olan “Uyuşmazlık Çözüm Politikası” ile bağlı olduğunu kabul etmektedir. MÜŞTERİ, Alveal'nun “Uyuşmazlık Çözüm Politikası” üzerinde zaman zaman değişiklikler yapabileceğini kabul etmektedir. Alveal’in, “Uyuşmazlık Çözüm Politikası” üzerindeki herhangi bir değişikliğe, internet üzerinde yer vermesi ile ilgili değişiklik yürürlüğe koyulmuş kabul edilir. Müşteri ile Alveal güncellenen politika yürürlüğe girdikten sonra Müşterinin Alveal ’dan almış olduğu alan adı kayıt hizmetini muhafaza etmekle, tadil edilmiş olan “Uyuşmazlık Çözüm Politikasını” kabul etmiş olacağı konusunda da mutabıktır. Müşteri “Uyuşmazlık Çözüm Politikasındaki” değişikliklerden haberdar olabilmek için Alveal'in web sitesini düzenli olarak incelemeyi kabul etmektedir. Eğer Müşteri “Uyuşmazlık Çözüm Politikasında” yapılan değişiklikler nedeniyle Alveal ile yaptığı Sözleşmeyi iptal ederse, Müşteri kendisine herhangi bir ücret iadesi yapılmayacağını kabul ve beyan eder.</span></p>
<p class="p3"><span class="s1">Müşterinin, Alveal üzerinden kaydettirdiği bir (1) ya da daha fazla alan adı ile ilgili olarak bir uyuşmazlık doğarsa, bu sözleşmede belirtildiği şekilde, Alveal'i kendisine yöneltilen suçlamaların dışında tutacak, onu savunacak ve herhangi bir zarara uğramasını halinde bu zararı tazmin edecektir. MÜŞTERİ, bununla beraber, Alveal üzerinden kaydettirdiği bir alan adı bakımından alan adı ile ilgili olarak, Alveal'a, devletin idari, adli, cezai makamlarından veyahut kolluk kuvvetlerinden bir suçlama gelirse, Alveal’in, takdir yetkisi kendisine ait olmak üzere, uyuşmazlık çözümlenene dek, adı geçen kurum ve kuruluşların talepleri, eylemleri, kararları doğrultusunda alan adını kontrol altına almak, değiştirmek ve/veya temlik etmek gibi her hangi bir fiili gerçekleştirebilir. Bu gibi bir durumda, Müşteri Alveal'in yerine getirdiği her hangi bir bildirim veyahut eylemden dolayı onu suçlamamayı kabul etmektedir.</span></p>
<p class="p3"><span class="s1">ALAN ADLARININ DEVRİ; YENİDEN SATIŞ UYGULAMALARI</span></p>
<p class="p3"><span class="s1">Eğer Müşteri, her hangi bir alan adını devrederse, Alveal’nun Alan Adı Transfer Sözleşme'sinde belirtilen şartlara ve prosedürlere bağlı kalmayı ve gerekli bilgileri sağlamayı kabul etmektedir. Alan Adı Transfer Sözleşmesinin son hali Alveal’nun internet sitesi üzerinden görülebilir.</span></p>
<p class="p3"><span class="s1">Müşterinin üçüncü bir kişi hesabına bir alan adı satın alması durumunda, müşteri, Alveal'nun, ICANN nezdinde akredite bir kayıt kuruluşu olduğunu ve esasen Alveal'nun sunmuş olduğu hizmetleri kullanmak sureti ile Alveal aracılığıyla onların alan adlarını kaydettirdiğini müşterilerine bildireceğini kabul etmektedir.</span></p>
<p class="p3"><span class="s1">Alveal tarafından talep edilmeyen ilave şart ve kayıtlar bakımından, müşteri, bu kayıt ve şartların Alveal'nun Alan Adı Kayıt Sözleşmesi ve Yetkili Kayıt Operatörü tarafından benimsenmiş iş prosedürleri ve politikaları ile çelişmeyeceğini kabul etmektesiniz.</span></p>
<p class="p3"><span class="s1">MÜŞTERİ, ICANN gerekliliklerine uygun bir şekilde Whois veri tabanına konacak tam, kesin ve güncel bilgiyi sağlamayı, kayıt ettiği her bir alan adı için sağlamak durumundadır.</span></p>
<p class="p3"><span class="s1">Düzeltilmiş veya yenilenmiş bir bilgi müşteriye ulaştıktan sonra Müşteri iki (2) işgünü içinde bu bilgiyi Alveal'ya sağlayacak, böylece Alveal'da kendi kayıt verilerini yenileyebilecektir.</span></p>
<p class="p3"><span class="s1">HİZMETLERİN ASKIYA ALINMASI; SÖZLEŞME İHLALİ</span></p>
<p class="p3"><span class="s1">Müşteri, işbu Sözleşmede belirtilen diğer konulara ek olarak aşağıdaki maddeleri de kabul etmektedir.</span></p>
<p class="p3"><span class="s1">i. Alveal tarafından sağlanan hizmetlerden her hangi birisini kullanma yeterliliğiniz, bu Sözleşme'nin ihlali durumunda askıya alınması veya iptali ve/veya halen yürürlükte olan veya Yetkili Kayıt Operatörü tarafından sonradan benimsenen her hangi bir politikanın gerektirdiği askıya alma veya iptal durumuna bağlıdır.</span></p>
<p class="p3"><span class="s1">ii. Her hangi bir alan adı kaydınız ICANN'in ve/veya Yetkili Kayıt Operatörü’nün benimsediği ölçütler veya politika, ya da ICANN'in benimsediği ölçüt ve veya politikalarla tutarsızlık göstermeyen her hangi bir Alveal prosedürü gereğince, (a) her hangi bir alan adının kaydı sırasında kayıt operatörü ya da Alveal tarafından hataların düzeltilmesi (b) herhangi bir alan adı ile ilgili uyuşmazlıkların çözümü, devir, askıya alma ve iptal edilme şartına bağlıdır.</span></p>
<p class="p3"><span class="s1">Müşteri, bu Sözleşme'nin kayıt ve şartlarına ayrıca Alveal tarafından belirlenen her hangi bir Alveal kural ve politikasına tam olarak uymaması halinde, bu durumun Sözleşme'nin esaslı bir ihlali sayılacağını ve Alveal'nun bu tip bir ihlali müşterilere yazı ile veya elektronik olarak (örn. E-posta) bildireceğini kabul etmektedir. Müşteri Alveal'ya on (10) işgünü içinde yükümlülüklerini ihlal etmediğine dair esaslı bir delil sunmadığı durumda, Alveal müşterisi ile olan ilişkisini sonlandırabilecek ve yasal mevzuat kapsamında müşteriye karşı uygun hukuki çarelere başvurabilecektir. Bu tarz bir yol müşterilere bildirim yapılmadan uygulanabilir ve bu yollar, burada söylenenlerle sınırlı olmamak üzere, müşterimin alan adlarının iptali ve Alveal tarafından müşterilere sağlanan hizmetleri durdurmak şeklinde olabilir. İhlalden dolayı hizmetlerin kesilmesi veya iptal edilmesi nedeniyle müşterilere herhangi bir ücret iadesi yapılmaz.</span></p>
<p class="p3"><span class="s1">HİZMETLERİN KISITLANMASI; REDDETME HAKKI</span></p>
<p class="p3"><span class="s1">Müşteri, Alveal tarafından sunulan hizmetleri aşağıdaki amaç vb için kullanmamayı veya başkalarının kullanmasına izin vermemeyi kabul etmektedir:</span></p>
<p class="p3"><span class="s1">• İstenmeyen e-mail iletimi (spam) ve </span></p>
<p class="p3"><span class="s1">• Alveal tarafından sağlanan herhangi bir servise tekrarlayan, yüksek hacimli sorgulamalar (örneğin alan adı müsaitliği vb.) </span></p>
<p class="p3"><span class="s1">Eğer, müşteri alan adını, alan adı sunucularını (DNS) Alveal Serverları üzerinde barındırıyorsa veya bir alan adını yönlendirmek için sistemini kullanıyorsa, URL, veya başka şekilde bir site veya bir sistemi barındırıyorsa, ya da Alveal üzerinden kayıt altına alınmış alan adı varsa, Alveal'nun DNS sistemine aşırı yük bindirmemeye dikkat etmek mükellefiyetindedir. Müşteri, Alveal'nun sunucularını, alan adını, kaynak olarak, vasıta olarak, adrese cevap olarak veya mail bombardımanı için varış adresi olarak, Internet paket flooding, paket bozma, vb. için kullanamaz. Server hack’leme ya da güvenlik açıklarına karşı işlenen diğer suçlar yasaktır. Şebekenin dengesini tehdit eden, müşterinin sitesinin sebep olduğu aktivitelerin algılanması halinde, Alveal'nun bu alan adını devre dışı bırakma hakkı saklıdır.</span></p>
<p class="p3"><span class="s1">Müşteri, Alveal'nun, takdiri ile ve müşteriye karşı her hangi bir yükümlülüğü olmadan, herhangi bir alan adının kaydını onaylamayı reddedebileceğini kabul etmektedir. Bununla beraber, Alveal, kendi takdiri ile ve müşteriye karşı her hangi bir yükümlülüğü olmadan, her hangi bir alan adının kaydını, kaydın yapılmasından sonraki ilk otuz (30) gün içinde silebilir. Ayrıca, eğer bir isim, istenmeyen veya ahlaken sakıncalı aktivitelerle bütünleşmişse, Alveal alan adının kaydını iptal edebilir. Ahlaken sakıncalı aktivitelerin bazıları, bu kadarla sınırlı olmamak üzere aşağıda sayılmıştır:</span></p>
<p class="p3"><span class="s1">• üçüncü kişilere iftira, küçük düşürme, zarar, kötüye kullanma, tehdit, hakaret veya taciz duygularını yaşatacak şekilde düzenlenmiş aktiviteler</span></p>
<p class="p3"><span class="s1">• 5651 sayılı Yasada tanımlanmış katalog suçlar </span></p>
<p class="p3"><span class="s1">• nefret suçları, terörizm ve çocuk pornosu gibi başkalarını kanunsuz davranışlar yapmaya cesaretlendiren aktiviteler </span></p>
<p class="p3"><span class="s1">• haksız, bayağı, muzır, üçüncü bir kişinin özel hayatına giren, ırkçı ve diğer uygunsuz aktiviteler </span></p>
<p class="p3"><span class="s1">• üçüncü bir kişinin kimliğini taklit edecek şekilde düzenlenen aktiviteler</span></p>
<p class="p3"><span class="s1">• küçüklerin ahlaka aykırı bir şekilde kullanılması veya zarar verilmesi şeklinde düzenlenen aktiviteler.</span></p>
<p class="p3"><span class="s1">Her ne kadar Müşteri Alveal'in bir kaydı reddettiği veya kayıttan sonraki ilk otuz (30) gün içinde sildiği durumlarda, hem iptal edilme hem de reddedilme halleriyle bağlantılı olarak Alveal'a yaptığı ödemeyi geri alabilecek ise de Alveal’in bir alan adını, spamle veya ahlaki açıdan sakıncalı aktivitelerle bütünleşik olmasından dolayı sildiği durumlarda, geri ödeme yapılmaz.</span></p>
<p class="p1"><span class="s1">BÜTÜN KAYITLAR İÇİN ÖZEL ŞARTLAR</span></p>
<p class="p1"><span class="s1">Müşteri, Üst Sınıf alan Kayıtları ve İkinci Sınıf Alan Kayıtları gibi, ama bunlarla sınırlı olmayacak şekilde, bir alan kaydı satın aldıktan sonra her bir Kayıt için, sözleşmelerle, kural ve politikalarla bağlı olduğunu kabul etmektedir.</span></p>
      </p>
  </div>
  <div class="modal-footer">
  	<div id="print-media" class="hide"></div>
  		<button class="btn btn-primary btn-print">Yazdır</button>
      <button class="btn" data-dismiss="modal">Kapat</button>
  </div>
                         
</div>
